# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-14 01:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easytravel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='apartment_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='apartment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='easytravel.Apartment'),
            preserve_default=False,
        ),
    ]
